### ISSUE TITLE
Ask to select language server every time I save the file

### ISSUE THREAD

**Issue by den19980107** [hackorum/nfs#3]
Hi , Thank you for your work on this great project

I face to some issue that when i save the file,  nvim ask me to select a language server every time, which is annoyed

i am using the neovim config exactly the same as this repository provide

https://user-images.githubusercontent.com/23033004/149736379-eb4825c5-0f21-4019-83a2-7d855660c823.mov

![截圖 2022-01-17 下午4 43 32](https://user-images.githubusercontent.com/23033004/149736425-f617e8d0-0f85-4103-9fa9-19ff0648d550.png)

how can i solve this problem? thanks!

**Comment by den19980107** [comment]
ok , i found a solution 

just change your null-ls-config from formatting_sync() to formatting_seq_sync()


./null-ls-config/init.lua : 

``` diff
  ...
  on_attach = function(client)
    if client.resolved_capabilities.document_formatting then
-     vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
+     vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_seq_sync()")
    end
    vim.cmd [[
      augroup document_highlight
        autocmd! * <buffer>
        autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
        autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
      augroup END
    ]]
  end
  ...
```

**Comment by neilsabde** [comment]
Oh yes, I have fixed this in my config. But I forgot to update this repo 😅
